load 'fichresultsplot'
load 'shfl6r.txt'
load 'shfl6s.txt'
load 'shfh6r.txt'
load 'shfh6s.txt'
figure(1)
loglog(fichresultsplot(:,4),fichresultsplot(:,5),...
       shfl6r(:,1),shfl6r(:,2),...
       shfl6s(:,1),shfl6s(:,2),...
       shfh6r(:,1),shfh6r(:,2),...
       shfh6s(:,1),shfh6s(:,2))