SOURCE=	ADDEXT.f BOLTING.f CONTACT.f CONTCF.f DATAIN.f \
		DRAGS.f DISPLAC.f EXCEED.f FABRIC.f \
		FIXED.f GRAP.f INDF.f INERTIA.f INTEG.f IPOS.f \
		JUDGEA.f JUDGEB.f LM.F90 MAIN.f MASS.f \
                MEMBRANE.f MOVING.f PIN.f POINT.f PSCHAR.f \
		PTLOAD.f PUN1.f PUNISH.f \
		RATIO.f RESTR.f RESULT.f SGN.f SEARCH.f \
 		SEARCH1.f SPARSE.f SPRING.f \
		STATIC.f TRANSF.f TRIDC.f VOLUMN.f XROTATIO.f
FFLAGS= -O 
dda: $(SOURCE) 
	gfortran -o dda $(FFLAGS) -I./ $(SOURCE) -C

